### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by rsoorajs** [wnxd/docker-v2ray#3]
showing error while building image.because v2ray changed there v2ray core downloading domain.pls fix it

**Comment by rsoorajs** [comment]
i tried to build image using this dockerfile..but keep failing

**Comment by wnxd** [comment]
Please use 93aed1d
If google is not accessible
Remove the comment "go env -w GOPROXY=https://goproxy.io,direct"

**Comment by rsoorajs** [comment]
> Please use [93aed1d](https://github.com/wnxd/docker-v2ray/commit/93aed1d5bce11e377d119916cb63e840cb5b2b22)
> If google is not accessible
> Remove the comment "go env -w GOPROXY=https://goproxy.io,direct"

Thank you..your repo is most simple and easy to use..really appreciate your work :)

**Comment by rsoorajs** [comment]
right now i am testing,i will close the issue after it works

**Comment by rsoorajs** [comment]
> Please use [93aed1d](https://github.com/wnxd/docker-v2ray/commit/93aed1d5bce11e377d119916cb63e840cb5b2b22)
> If google is not accessible
> Remove the comment "go env -w GOPROXY=https://goproxy.io,direct"

getting these  errors on your last update @wnxd 

![IMG_20210124_222629_938](https://user-images.githubusercontent.com/20116017/105637384-4bcf1c80-5e93-11eb-8eb9-4b4b5c942f7c.jpg)
![IMG_20210124_222625_704](https://user-images.githubusercontent.com/20116017/105637386-4e317680-5e93-11eb-8b61-3e87af94db47.jpg)

**Comment by wnxd** [comment]
Alpine new version use `/etc/os-release`
V2ray build use `CGO_ENABLED=0`
b2a5935

**Comment by rsoorajs** [comment]
Thank you for your fix.working now
